// Shared context for lazily-loaded tab panels (refactor step 2).
// AppShell owns all state/handlers and provides them via panelCtx;
// panels consume them through a single typed destructure.

import React from 'react';
import type {
  SessionMeta, Campaign, Contact, Group, AutoRule, AuditLog, ChatItem, ChatMessage,
  FollowUpTask, Sequence, SalesAnalytics, AutoReplyConfig, SystemStatus,
  IntegrationConfig, OutgoingWebhook, IntegrationLog, PrivacySettings
} from '../types';
import type { ToastType } from '../components/toast';
import type { Language } from '../i18n';

export type TabKey = 'dashboard' | 'sessions' | 'chats' | 'crm' | 'contacts' | 'groups' | 'campaigns' | 'tester' | 'automation' | 'integrations' | 'infrastructure' | 'logs';

export interface PanelCtx {
  t: any;
  lang: Language;
  privacyMode: boolean;
  setPrivacyMode: React.Dispatch<React.SetStateAction<boolean>>;
  privacySettings: PrivacySettings;
  setPrivacySettings: React.Dispatch<React.SetStateAction<PrivacySettings>>;
  isPrivacyMenuOpen: boolean;
  setIsPrivacyMenuOpen: (v: boolean) => void;
  showToast: (message: string, type?: ToastType) => void;
  appConfirm: (message: string, options?: { confirmLabel?: string; cancelLabel?: string; danger?: boolean }) => Promise<boolean>;
  previewTemplate: (template: string, sampleName?: string) => string;
  addLog: (text: string, type?: 'info' | 'success' | 'warn') => void;
  messagesEndRef: React.RefObject<HTMLDivElement | null>;
  liveLogs: Array<{ id: string; time: string; text: string; type: 'info' | 'success' | 'warn' }>;
  sessions: SessionMeta[];
  selectedSessionId: string;
  setSelectedSessionId: (v: string) => void;
  campaigns: Campaign[];
  contacts: Contact[];
  setContacts: React.Dispatch<React.SetStateAction<Contact[]>>;
  groups: Group[];
  rules: AutoRule[];
  activeSession: SessionMeta | null;
  isGlobalConnected: boolean;
  setActiveTab: (tab: TabKey) => void;
  fetchSessions: () => Promise<void>;
  fetchSystemStatus: () => Promise<void>;
  fetchCampaigns: () => Promise<void>;
  fetchContacts: (sessionId: string) => Promise<void>;
  fetchGroups: (sessionId: string) => Promise<void>;
  fetchChats: (sessionId: string) => Promise<void>;
  fetchChatMessages: (sessionId: string, chatJid: string) => Promise<void>;
  fetchTags: (sessionId: string) => Promise<void>;
  fetchCRMTasks: (sessionId: string) => Promise<void>;
  fetchCRMSequences: (sessionId: string) => Promise<void>;
  fetchSalesAnalytics: (sessionId: string, range?: 'today' | '7d' | '30d' | '90d' | 'all') => Promise<void>;
  fetchAuditLogs: () => Promise<void>;
  fetchBackups: () => Promise<void>;
  fetchIntegrationLogs: () => Promise<void>;
  chats: ChatItem[];
  setChats: React.Dispatch<React.SetStateAction<ChatItem[]>>;
  activeChatJid: string | null;
  setActiveChatJid: (v: string | null) => void;
  chatMessages: ChatMessage[];
  setChatMessages: React.Dispatch<React.SetStateAction<ChatMessage[]>>;
  chatSearchQuery: string;
  setChatSearchQuery: (v: string) => void;
  chatsSidebarTab: 'chats' | 'contacts' | 'groups' | 'channels';
  setChatsSidebarTab: (v: 'chats' | 'contacts' | 'groups' | 'channels') => void;
  chatFilter: 'all' | 'personal' | 'groups' | 'channels' | 'unread';
  setChatFilter: (v: 'all' | 'personal' | 'groups' | 'channels' | 'unread') => void;
  chatReplyText: string;
  setChatReplyText: (v: string) => void;
  isNewChatModal: boolean;
  setIsNewChatModal: (v: boolean) => void;
  newChatPhone: string;
  setNewChatPhone: (v: string) => void;
  isRefreshingChats: boolean;
  refreshSuccess: boolean;
  isRefreshingThread: boolean;
  setIsRefreshingThread: (v: boolean) => void;
  isSendMediaModal: boolean;
  setIsSendMediaModal: (v: boolean) => void;
  chatMediaFile: File | null;
  setChatMediaFile: (v: File | null) => void;
  chatMediaCaption: string;
  setChatMediaCaption: (v: string) => void;
  unreadChatsCount: number;
  contactsMap: Map<string, Contact>;
  groupsMap: Map<string, Group>;
  filteredChats: ChatItem[];
  filteredContacts: Contact[];
  filteredGroups: Group[];
  filteredChannels: ChatItem[];
  findContact: (phoneOrJid?: string | null) => Contact | null;
  handleManualRefreshChats: () => Promise<void>;
  handleRefreshActiveThread: () => Promise<void>;
  handleSendChatMessage: (textOverride?: string) => Promise<void>;
  handleSendChatMedia: () => Promise<void>;
  handleStartNewChat: () => void;
  botConfig: AutoReplyConfig;
  setBotConfig: React.Dispatch<React.SetStateAction<AutoReplyConfig>>;
  handleToggleAutoReplyGlobal: (enabled: boolean) => Promise<void>;
  setIsChatAutoReplyModal: (v: boolean) => void;
  setIsChatBroadcastModal: (v: boolean) => void;
  sessionSearchQuery: string;
  setSessionSearchQuery: (v: string) => void;
  sessionStatusFilter: string;
  setSessionStatusFilter: (v: string) => void;
  copiedPairingCode: boolean;
  setCopiedPairingCode: (v: boolean) => void;
  abHealth: Record<string, { stats: any; events: any[] }>;
  abResetting: string | null;
  handleResetCircuitBreaker: (sessionId: string) => Promise<void>;
  handleDisconnectSession: (id: string) => Promise<void>;
  handleLogoutSession: (id: string) => Promise<void>;
  handleDeleteSession: (id: string) => Promise<void>;
  handleConnectSessionDirect: (id: string) => Promise<void>;
  activeQrModal: { open: boolean; session: SessionMeta | null };
  setActiveQrModal: (v: { open: boolean; session: SessionMeta | null }) => void;
  connectOptionModal: { open: boolean; sessionId: string; method: 'qr' | 'pairing'; phone: string };
  setConnectOptionModal: (v: { open: boolean; sessionId: string; method: 'qr' | 'pairing'; phone: string }) => void;
  crmStageFilter: 'ALL' | 'lead' | 'prospect' | 'customer' | 'churned';
  setCrmStageFilter: (v: 'ALL' | 'lead' | 'prospect' | 'customer' | 'churned') => void;
  crmSearchQuery: string;
  setCrmSearchQuery: (v: string) => void;
  crmTasks: FollowUpTask[];
  crmTaskFilter: 'ALL' | 'PENDING' | 'COMPLETED' | 'CANCELLED';
  setCrmTaskFilter: (v: 'ALL' | 'PENDING' | 'COMPLETED' | 'CANCELLED') => void;
  crmSequences: Sequence[];
  crmAnalytics: SalesAnalytics | null;
  crmTimeRange: 'today' | '7d' | '30d' | '90d' | 'all';
  setCrmTimeRange: (v: 'today' | '7d' | '30d' | '90d' | 'all') => void;
  crmAutoDispatch: boolean;
  handleToggleCrmAutoDispatch: () => Promise<void>;
  isNewTaskModal: boolean;
  setIsNewTaskModal: (v: boolean) => void;
  newTaskPhone: string;
  setNewTaskPhone: (v: string) => void;
  newTaskName: string;
  setNewTaskName: (v: string) => void;
  newTaskTitle: string;
  setNewTaskTitle: (v: string) => void;
  newTaskTemplate: string;
  setNewTaskTemplate: (v: string) => void;
  newTaskDueHours: number;
  setNewTaskDueHours: (v: number) => void;
  handleCreateFollowUpTask: () => Promise<void>;
  handleExecuteFollowUp: (taskId: string) => Promise<void>;
  handleCancelFollowUp: (taskId: string) => Promise<void>;
  handleDeleteFollowUp: (taskId: string) => Promise<void>;
  isApplySeqModal: boolean;
  setIsApplySeqModal: (v: boolean) => void;
  applySeqContact: Contact | null;
  setApplySeqContact: (v: Contact | null) => void;
  selectedSeqId: string;
  setSelectedSeqId: (v: string) => void;
  handleApplySequence: () => Promise<void>;
  isNotesModal: boolean;
  setIsNotesModal: (v: boolean) => void;
  selectedContactForNotes: Contact | null;
  setSelectedContactForNotes: (v: Contact | null) => void;
  contactNotesText: string;
  setContactNotesText: (v: string) => void;
  handleSaveContactNotes: () => Promise<void>;
  contactSearchQuery: string;
  setContactSearchQuery: (v: string) => void;
  availableTags: Array<{ tag: string; count: number }>;
  selectedTagFilter: string;
  setSelectedTagFilter: (v: string) => void;
  isAddContactModal: boolean;
  setIsAddContactModal: (v: boolean) => void;
  newContactPhone: string;
  setNewContactPhone: (v: string) => void;
  newContactName: string;
  setNewContactName: (v: string) => void;
  newContactTags: string;
  setNewContactTags: (v: string) => void;
  handleAddContact: () => Promise<void>;
  isEditContactTagsModal: boolean;
  setIsEditContactTagsModal: (v: boolean) => void;
  editingContactPhone: string;
  editingContactName: string;
  editingContactTags: string;
  setEditingContactTags: (v: string) => void;
  setEditingContactPhone: (v: string) => void;
  setEditingContactName: (v: string) => void;
  setIsAddSessionModal: (v: boolean) => void;
  setChatBroadcastSessionId: (v: string) => void;
  fetchIntegrationConfigs: () => Promise<void>;
  fetchOutgoingWebhooks: () => Promise<void>;
  setEditRuleId: (v: string) => void;
  openEditTagsModal: (contact: Contact) => void;
  handleSaveContactTags: () => Promise<void>;
  handleToggleOptOut: (phone: string, currentStatus: boolean) => Promise<void>;
  handleDeleteContact: (phone: string) => Promise<void>;
  handleImportGroupToContacts: (jid: string) => Promise<void>;
  handleUpdateContactStage: (phone: string, stage: 'lead' | 'prospect' | 'customer' | 'churned') => Promise<void>;
  handleOpenChatWithContact: (phone: string, name?: string) => void;
  isNewCampaignModal: boolean;
  setIsNewCampaignModal: (v: boolean) => void;
  campName: string;
  setCampName: (v: string) => void;
  campAudienceMode: 'group' | 'manual';
  setCampAudienceMode: (v: 'group' | 'manual') => void;
  campSelectedTag: string;
  setCampSelectedTag: (v: string) => void;
  campTemplate: string;
  setCampTemplate: (v: string) => void;
  campRecipientsRaw: string;
  setCampRecipientsRaw: (v: string) => void;
  campRandomDelayMin: number;
  setCampRandomDelayMin: (v: number) => void;
  campRandomDelayMax: number;
  setCampRandomDelayMax: (v: number) => void;
  messageTemplates: Array<{ id: string; name: string; category: string; content: string }>;
  handleCreateCampaign: () => Promise<void>;
  handleStartCampaign: (id: string) => Promise<void>;
  handlePauseCampaign: (id: string) => Promise<void>;
  handleDeleteCampaign: (id: string) => Promise<void>;
  isViewRecipientsModal: boolean;
  setIsViewRecipientsModal: (v: boolean) => void;
  viewRecipientsList: any[];
  viewCampaignTitle: string;
  handleViewRecipients: (id: string, title: string) => Promise<void>;
  handleFillRecipientsFromGroup: () => Promise<void>;
  isNewRuleModal: boolean;
  setIsNewRuleModal: (v: boolean) => void;
  ruleName: string;
  setRuleName: (v: string) => void;
  ruleTriggerText: string;
  setRuleTriggerText: (v: string) => void;
  ruleOperator: 'contains' | 'equals' | 'starts_with' | 'regex';
  setRuleOperator: (v: 'contains' | 'equals' | 'starts_with' | 'regex') => void;
  ruleReplyText: string;
  setRuleReplyText: (v: string) => void;
  ruleAddTagEnabled: boolean;
  setRuleAddTagEnabled: (v: boolean) => void;
  ruleActionTag: string;
  setRuleActionTag: (v: string) => void;
  ruleSetStageEnabled: boolean;
  setRuleSetStageEnabled: (v: boolean) => void;
  ruleActionStage: 'lead' | 'prospect' | 'customer' | 'churned';
  setRuleActionStage: (v: 'lead' | 'prospect' | 'customer' | 'churned') => void;
  isEditRuleModal: boolean;
  setIsEditRuleModal: (v: boolean) => void;
  editRuleId: string;
  editRuleName: string;
  setEditRuleName: (v: string) => void;
  editRuleTriggerText: string;
  setEditRuleTriggerText: (v: string) => void;
  editRuleOperator: 'contains' | 'equals' | 'starts_with' | 'regex';
  setEditRuleOperator: (v: 'contains' | 'equals' | 'starts_with' | 'regex') => void;
  editRuleReplyText: string;
  setEditRuleReplyText: (v: string) => void;
  editRuleAddTagEnabled: boolean;
  setEditRuleAddTagEnabled: (v: boolean) => void;
  editRuleActionTag: string;
  setEditRuleActionTag: (v: string) => void;
  editRuleSetStageEnabled: boolean;
  setEditRuleSetStageEnabled: (v: boolean) => void;
  editRuleActionStage: 'lead' | 'prospect' | 'customer' | 'churned';
  setEditRuleActionStage: (v: 'lead' | 'prospect' | 'customer' | 'churned') => void;
  simTestInput: string;
  setSimTestInput: (v: string) => void;
  simMatchedRule: AutoRule | null;
  simEvaluatedReply: string;
  handleToggleRule: (id: string, currentActive: boolean) => Promise<void>;
  handleCreateRule: () => Promise<void>;
  handleSaveEditRule: () => Promise<void>;
  handleDeleteRule: (id: string) => Promise<void>;
  handleSaveBotConfig: () => Promise<void>;
  testerType: 'text' | 'media' | 'poll' | 'location' | 'contact';
  setTesterType: (v: 'text' | 'media' | 'poll' | 'location' | 'contact') => void;
  testerRecipient: string;
  setTesterRecipient: (v: string) => void;
  testerMessage: string;
  setTesterMessage: (v: string) => void;
  testerMediaFile: File | null;
  setTesterMediaFile: (v: File | null) => void;
  testerMediaCaption: string;
  setTesterMediaCaption: (v: string) => void;
  testerPollName: string;
  setTesterPollName: (v: string) => void;
  testerPollValues: string;
  setTesterPollValues: (v: string) => void;
  testerPollMulti: number;
  setTesterPollMulti: (v: number) => void;
  testerLatitude: string;
  setTesterLatitude: (v: string) => void;
  testerLongitude: string;
  setTesterLongitude: (v: string) => void;
  testerLocName: string;
  setTesterLocName: (v: string) => void;
  testerLocAddress: string;
  setTesterLocAddress: (v: string) => void;
  testerContactName: string;
  setTesterContactName: (v: string) => void;
  testerContactPhone: string;
  setTesterContactPhone: (v: string) => void;
  testerContactOrg: string;
  setTesterContactOrg: (v: string) => void;
  testerLoading: boolean;
  testerResponse: any;
  handleRunTester: () => Promise<void>;
  integrationConfigs: IntegrationConfig[];
  outgoingWebhooks: OutgoingWebhook[];
  integrationLogs: IntegrationLog[];
  selectedIntegrationTab: 'google_form' | 'woocommerce' | 'cf7' | 'elementor' | 'caldera' | 'formidable' | 'outgoing' | 'logs';
  setSelectedIntegrationTab: (v: 'google_form' | 'woocommerce' | 'cf7' | 'elementor' | 'caldera' | 'formidable' | 'outgoing' | 'logs') => void;
  copiedWebhookUrl: boolean;
  setCopiedWebhookUrl: (v: boolean) => void;
  copiedScriptCode: boolean;
  setCopiedScriptCode: (v: boolean) => void;
  isTestIntegrationModal: boolean;
  setIsTestIntegrationModal: (v: boolean) => void;
  testIntegrationPhone: string;
  setTestIntegrationPhone: (v: string) => void;
  testIntegrationName: string;
  setTestIntegrationName: (v: string) => void;
  testIntegrationFormName: string;
  setTestIntegrationFormName: (v: string) => void;
  testIntegrationResult: any;
  testIntegrationLoading: boolean;
  handleTestIncomingWebhook: () => Promise<void>;
  handleSaveIntegrationConfig: (conf: Partial<IntegrationConfig>) => Promise<void>;
  handleTestOutgoingWebhook: (id: string) => Promise<void>;
  handleCreateOutgoingWebhook: () => Promise<void>;
  handleDeleteOutgoingWebhook: (id: string) => Promise<void>;
  isAddOutgoingWebhookModal: boolean;
  setIsAddOutgoingWebhookModal: (v: boolean) => void;
  newWebhookName: string;
  setNewWebhookName: (v: string) => void;
  newWebhookUrl: string;
  setNewWebhookUrl: (v: string) => void;
  newWebhookSecret: string;
  setNewWebhookSecret: (v: string) => void;
  newWebhookEvents: string[];
  editIntegrationConfig: IntegrationConfig | null;
  setEditIntegrationConfig: (v: IntegrationConfig | null) => void;
  isEditIntegrationModal: boolean;
  setIsEditIntegrationModal: (v: boolean) => void;
  systemStatus: SystemStatus | null;
  backups: any[];
  handleCreateBackup: () => Promise<void>;
  auditLogs: AuditLog[];
  logFilter: string;
  setLogFilter: (v: string) => void;
}
